### ISSUE TITLE
Idea: Calculate path for arrows shooted by other entities

### ISSUE THREAD

**Issue by DatArnoGuy** [sefirosweb/minecraftHawkEye#13]
Basically what the title says. It would be awesome, if bot was able to calculate flight paths for other entities arrows. This would allow bot to dodge arrows, if they were going to hit him. Just an idea, maybe bit out of the box for this plugin, but just maybe.

What you think?

**Comment by sefirosweb** [comment]
Hello this topic I thought about it too, but I think it could be somewhat complicated and a lot of CPU cost

Also the arrows in (short range) as soon as the bot has time to react and move,

My idea is to "raise" the shield =P

Keep subscribe maybe I can do some eventemitter for that

**Comment by Pandapip1** [comment]
This would be better put in https://github.com/Nixes/mineflayer-bloodhound

**Comment by sefirosweb** [comment]
Hi! I added some events and function to detect the arrow are incoming to bot!
![image](https://user-images.githubusercontent.com/20754836/223176351-3f7400cf-8239-4fa4-b1d1-0757dbbecb47.png)
```ts
   bot.on('target_aiming_at_you', (entity, arrowTrajectory) => {
      // XXX
    })  
```
You can take a look to raise shield example:
// Need to start "radar", because this use a lot of CPU, it is not recomended to enable all time
https://github.com/sefirosweb/minecraftHawkEye/blob/cd98213108d8dfbfb551b6874db5f8fea711050f/examples/shield_up.ts#L36

https://github.com/sefirosweb/minecraftHawkEye/blob/04ee323997258eb8644b3c42dda36ba053e94a59/examples/shield_up.ts#L47-L48

Also I published the function for calculate some arrow for some direction:
```ts
bot.hawkEye.calculateArrowTrayectory(currentPos: Vec3, itemSpeed: number, pitch: number, yaw: number, ammunitionType?: Weapons)
```

https://github.com/sefirosweb/minecraftHawkEye/blob/cd98213108d8dfbfb551b6874db5f8fea711050f/src/calculateArrowTrayectory.ts#L8

Aslo I rewrite all code to TS , with fixesd of types and small bugs

**Comment by sefirosweb** [comment]
Check if the new version is fine to you
